### ISSUE TITLE
use in electron, Error: Invalid package 

### ISSUE THREAD

**Issue by coloz** [materiahq/ngx-monaco-editor#99]
```
materia-ui-ngx-monaco-editor.mjs:50 Error loading monaco-editor:  Error: Invalid package D:\Git\b4a\node_modules\electron\dist\resources\electron.asar
    at createError (node:electron/js2c/asar_bundle:5:1551)
    at fsReadFileAsar (node:electron/js2c/asar_bundle:5:7594)
    at Object.e.readFile (node:electron/js2c/asar_bundle:5:8838)
    at e._readSourceAndCachedData (loader.js:7:4088)
    at e.load (loader.js:7:2033)
    at e.load (loader.js:6:10698)
    at c (loader.js:8:10300)
    at s._loadModule (loader.js:8:10430)
    at s._resolve (loader.js:9:452)
    at s.defineModule (loader.js:8:6142)
```

**Comment by coloz** [comment]
but, use in browser or build to exe, it is ok.
